cache:
  directory: ~/app/cache/
  enabled: true
  
router:
  global_router: ~/app/config/router/external.yml
  format: yaml
  
web:
  root: chroot
  
services:
    directory: ~/app/config/services/
    file:     globally.yml
    
general:
  passphrase: abc
  run:
    user: xlix
    group: none
    
request:
  session_dir: ~/app/cache/sessions
  