cache:
  directory: ~/app/cache/
  enabled: true
  
web:
  root: ~/chroot/
  
services:
    directory: ~/app/config/services/
    file:     globally.yml
    
general:

  passphrase: abc
  run:
    user: xlix
    group: ~
    
request:
  session_dir: ~/app/cache/sessions
  