_main:
  match: /
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController:static:index
    
_second:
  match: /abc/sdg/{as}/{to}/{my}/{some}
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController::some