_main:
  match: /
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController:static:index
    
_second:
  match: /test/{number}/{image}/location
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\heUpdateController::some