_main:
  match: /
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController:static:index
    
_second:
  match: /abc/sdg/{some}/{content}/{from}
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController::index