_main:
  match: /
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController:static:index
  params:
    - ~
    - file
    
_second:
  match: /abc
  via:
    - ~
    - GET
    - PUT
    - POST
    - DELETE
  to: Core\Controller\IndexController::index
  params:
    - file