parameters:
   logwriter.class: \Monolog\Handler\StreamHandler
   logwriter.log: %kernel.root%/logs/app.log
   log.class: \Monolog\Logger
   request.class: \Symfony\Component\HttpFoundation\Request
   response.class: \Symfony\Component\HttpFoundation\Response
   twig.filesystem.class: \Twig_Loader_Filesystem
   twig.environment: \Twig_Environment
   
services:
  logwriter:
    class: %logwriter.class%
    arguments: [%logwriter.log%,\Monolog\Logger::Warning]
  log:
    class: %log.class%
    arguments: [%monolog.name%]
    calls:
      - [pushHandler, [@logwriter]]
      
  response:
    class: %response.class%
  reqfaq:
    class: %request.class%
  request:
    class: %request.class%
    factory_service: reqfaq
    factory_method: createFromGlobals
    
  twigfserror:
    class: %twig.filesystem.class%
    arguments: [%errorhandling.directory%] 
  twigerror:
    class: %twig.environment%
    arguments: [@twigfserror, {cache : %cache.error_dir%}]
  twigfsnormal:
    class: %twig.filesystem.class%
    arguments: [%cache.templ_dir%]
  twignormal:
    class: %twig.environment%
    arguments: [@twigfsnormal, {cache : %cache.templ_dir%}]
    


