parameters:
   logwriter.class: \Monolog\Handler\StreamHandler
   logwriter.log: %kernel.root%/logs/app.log
   log.class: \Monolog\Logger
   request.class: \Lib\Request\Request
   
services:
  logwriter:
    class: %logwriter.class%
    arguments: [%logwriter.log%,\Monolog\Logger::Warning]
  log:
    class: %log.class%
    arguments: [%monolog.name%]
    calls:
      - [pushHandler, [@logwriter]]
  request:
    class: %request.class%
    calls:
      - [fromGlobals]